nav:
    - Introduction: index.md
    - Primer-What-Every-Programmer-Should-Know-About-Memory: Primer-What-Every-Programmer-Should-Know-About-Memory
    - Memory-alignment: Memory-alignment
    #################### 字的概念####################    
    - Word: Word
    #################### 大小端的概念####################        
    - Endianess: Endianess
    - Memory-ordering: Memory-ordering
    - Memory-disambiguation: Memory-disambiguation
    - Atomic: Atomic