nav:
    - Introduction: index.md
    - Primer-What-Every-Programmer-Should-Know-About-Memory: Primer-What-Every-Programmer-Should-Know-About-Memory
    #################### 字的概念####################    
    - Word: Word    
    #################### 大小端的概念####################        
    - Memory-alignment: Memory-alignment    
    - Endianess: Endianess
    - Memory-ordering: Memory-ordering
    - Memory-disambiguation: Memory-disambiguation
    - Memory-access-instruction: Memory-access-instruction
