nav:
    - Instruction-set-architecture: Instruction-set-architecture.md
    - Machine-code: Machine-code.md
    - Architecture: Architecture
    - Comparison-of-instruction-set-architectures: Comparison-of-instruction-set-architectures.md