nav:
    - Introduction: index.md
    - Classification: Classification
    - Manufacturer: Manufacturer
    - Comparison-of-instruction-set-architectures: Comparison-of-instruction-set-architectures.md