nav:
    - Introduction: index.md
    #################### CPU####################    
    - CPU: CPU.md
    #################### 指令集的概念####################    
    - Instruction-set-architectures: Instruction-set-architectures
    #################### CPU的组成###################    
    - Components: Components

#################### 指令周期的概念####################    
    - Execution-of-instruction: Execution-of-instruction
    - Parallel-computing: Parallel-computing
    - Optimization: Optimization
    - Manufacturer: Manufacturer