nav:
    - Introduction: index.md
    - Tendency-toward-parallel-computing: Tendency-toward-parallel-computing    
    - Multiprocessing: Multiprocessing
    - Multicore-and-multiprocessor: Multicore-and-multiprocessor
    - 流水线-超标量-微码-多发射简介: 流水线-超标量-微码-多发射简介
