nav:
    - Computer-architecture: index.md
    - Stored-program-computer: Stored-program-computer
    - Von-Neumann-architecture: Von-Neumann-architecture
    - Harvard-architecture: Harvard-architecture
    - Universal-Turing-machine: Universal-Turing-machine.md
    - TODO-Turing-machine-VS-Von-Neuman-machine: TODO-Turing-machine-VS-Von-Neuman-machine.md
    - TODO-Von-neumann-architecture-VS-Harvard-architecture: TODO-Von-neumann-architecture-VS-Harvard-architecture.md