nav:
    - Introduction: index.md
    - Data-alignment-Straighten-up-and-fly-right: Data-alignment-Straighten-up-and-fly-right.md
    - Memory-alignment: Memory-alignment.md
    - Purpose-of-memory-alignment: Purpose-of-memory-alignment.md