nav:
    - Introduction: index.md
    - Memory–access: Memory–access.md
    - Memory-alignment: Memory-alignment
    #################### 字的概念####################    
    - Word: Word
    #################### 大小端的概念####################        
    - Endianess: Endianess