nav:
    - Introduction: index.md
    - gotw-The-Free-Lunch-Is-Over-A-Fundamental-Turn-Toward-Concurrency-in-Software: gotw-The-Free-Lunch-Is-Over-A-Fundamental-Turn-Toward-Concurrency-in-Software    
    - The-New-C++Lay-down-your-guns-knives-and-clubs: The-New-C++Lay-down-your-guns-knives-and-clubs