nav:
    - Introduction: index.md
    - Multiprocessing: Multiprocessing
    - Multicore-and-multiprocessor: Multicore-and-multiprocessor
    - Coordination: Coordination
    - Tendency-toward-parallel-computing: Tendency-toward-parallel-computing
