nav:
    - Introduction: index.md
    - Multiprocessing: Multiprocessing
    - Multicore-and-multiprocessor: Multicore-and-multiprocessor
    - Coordination: Coordination
    - gotw-The-Free-Lunch-Is-Over-A-Fundamental-Turn-Toward-Concurrency-in-Software: gotw-The-Free-Lunch-Is-Over-A-Fundamental-Turn-Toward-Concurrency-in-Software